apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: noobaa
  namespace: openshift-storage
spec:
 dbResources:
   requests:
     cpu: '0.1'
     memory: 1Gi
 dbType: postgres
 coreResources:
   requests:
     cpu: '0.1'
     memory: 1Gi