apiVersion: quay.redhat.com/v1
kind: QuayIntegration
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  name: quay-bridge
spec:
  credentialsSecret:
    name: quay-credentials
    namespace: quay-registry
  clusterID: openshift
  insecureRegistry: true
  quayHostname: >-
    https://quay-registry-quay-quay-registry.apps.cluster-w5n52.w5n52.sandbox419.opentlc.com
