apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 00_openshift-local-storage-namespace.yaml
- 00_quay-namespace.yaml
- 01_openshift-local-storage-og.yaml
- 02_local-storage-operator-subscription.yaml
- 02_quay-operator.subscription.yaml
- 03_noobaa.yaml
- 03_quay-registry.yaml
- 04_noobaa-pv-backing-store.yaml
- 05_noobaa-obc.yaml
