apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: compliance-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"policy.open-cluster-management.io/v1","kind":"Policy","metadata":{"annotations":{"argocd.argoproj.io/sync-options":"SkipDryRunOnMissingResource=true","policy.open-cluster-management.io/categories":"CA
      Security Assessment and
      Authorization","policy.open-cluster-management.io/controls":"CA-2 Security
      Assessments, CA-7 Continuous
      Monitoring","policy.open-cluster-management.io/standards":"NIST SP
      800-53"},"labels":{"app.kubernetes.io/instance":"policy-00"},"name":"compliance-operator","namespace":"openshift-operators"},"spec":{"disabled":false,"policy-templates":[{"objectDefinition":{"apiVersion":"policy.open-cluster-management.io/v1","kind":"ConfigurationPolicy","metadata":{"name":"comp-operator-ns"},"spec":{"object-templates":[{"complianceType":"musthave","objectDefinition":{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"openshift-compliance"}}}],"remediationAction":"enforce","severity":"high"}}},{"objectDefinition":{"apiVersion":"policy.open-cluster-management.io/v1","kind":"ConfigurationPolicy","metadata":{"name":"comp-operator-operator-group"},"spec":{"object-templates":[{"complianceType":"musthave","objectDefinition":{"apiVersion":"operators.coreos.com/v1","kind":"OperatorGroup","metadata":{"name":"compliance-operator","namespace":"openshift-compliance"},"spec":{"targetNamespaces":["openshift-compliance"]}}}],"remediationAction":"enforce","severity":"high"}}},{"objectDefinition":{"apiVersion":"policy.open-cluster-management.io/v1","kind":"ConfigurationPolicy","metadata":{"name":"comp-operator-subscription"},"spec":{"object-templates":[{"complianceType":"musthave","objectDefinition":{"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"name":"compliance-operator","namespace":"openshift-compliance"},"spec":{"installPlanApproval":"Automatic","name":"compliance-operator","source":"redhat-operators","sourceNamespace":"openshift-marketplace"}}}],"remediationAction":"enforce","severity":"high"}}},{"objectDefinition":{"apiVersion":"policy.open-cluster-management.io/v1","kind":"ConfigurationPolicy","metadata":{"name":"comp-operator-status"},"spec":{"object-templates":[{"complianceType":"musthave","objectDefinition":{"apiVersion":"operators.coreos.com/v1alpha1","kind":"ClusterServiceVersion","metadata":{"namespace":"openshift-compliance"},"spec":{"displayName":"Compliance
      Operator"},"status":{"phase":"Succeeded"}}}],"remediationAction":"enforce","severity":"high"}}}],"remediationAction":"enforce"}}
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
    policy.open-cluster-management.io/standards: NIST SP 800-53
  creationTimestamp: 2023-07-25T12:24:13Z
  generation: 2
  labels:
    app.kubernetes.io/instance: policy-00
  managedFields:
  resourceVersion: "371996"
  uid: 7c1f2e0f-c7a8-4ccb-8ef2-a6a3336836eb
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-ns
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-compliance
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-operator-group
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: compliance-operator
                  namespace: openshift-compliance
                spec:
                  targetNamespaces:
                    - openshift-compliance
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-subscription
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: compliance-operator
                  namespace: openshift-compliance
                spec:
                  name: compliance-operator
                  installPlanApproval: Automatic
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-status
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: openshift-compliance
                spec:
                  displayName: Compliance Operator
                status:
                  phase: Succeeded
          remediationAction: enforce
          severity: high
  remediationAction: enforce
status: {}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: compliance-operator-placement
  namespace: openshift-operators
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: vendor
              operator: In
              values:
                - OpenShift
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: compliance-operator-placement-binding
  namespace: openshift-operators
placementRef:
  name: compliance-operator-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: compliance-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy
